apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170616031
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170616031
    app.kubernetes.io/part-of: test-app-170616031
  name: java-quarkus-170616031
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170616031
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170616031
    spec:
      containers:
      - image: quay.io/hacdev/ynlxzgu0-tenant/test-app-170616031/java-quarkus-170616031@sha256:b006186f5b2d7e75381afaff6d316c8896d3ef6bac10ce79a46bf1e37ec0fcaa
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
